pio := "/home/vagarth/.platformio/penv/bin/pio"

build:
    {{pio}} run

upload:
    {{pio}} run --target upload

monitor:
    {{pio}} device monitor

upload-monitor:
    {{pio}} run --target upload && {{pio}} device monitor

deploy:
    {{pio}} run
    scp .pio/build/esp32-c3-devkitc-02/firmware.bin vagarth@vagarth-server:/home/vagarth/hi-light-firmware/firmware.bin

ota device_id:
    mqttx pub -h mqtt.vagarth.dev -p 443 -l wss --path /mqtt -t "hilight/{{device_id}}/ota" -m "https://hi-light-fw.vagarth.dev/firmware.bin?t=$(date +%s)"
